### ISSUE TITLE
Simplify the process of accessing the simulations

### ISSUE THREAD

**Issue by 1cosmologist** [litebird/litebirdXS4#12]
Currently the simulations are split in at least two different format (fits, npy). We require two different python packages maps and chwide_maps to query the npy files at runtime. Unforturnately the information about these packages and their dependencies are unclear and scattered between multiple sections. It would be helpful if there is a master document clarifying what are the minimal set of steps and dependecies that are needed to access the simulations. Note that maps package seems to require two instrument model tables which one has to trace down. I still don't have the Litebird table. Can all of these be put together in a single package with a clear documentation.

**Comment by zonca** [comment]
which simulations are you specifically referring to?

**Comment by 1cosmologist** [comment]
CMB simulations for S4 channels, S4 CHWIDE noise maps. The foregrounds are straightforward to access as these are 
fits files.

**Comment by 1cosmologist** [comment]
In particular I use `maps.get_s4_map` and `chwide_maps.noise.get_sim_tqumap` to access these simulations.

**Comment by zonca** [comment]
@carronj  would you be able to add more documentation on https://github.com/litebird/litebirdXS4/tree/master/20231114_map-based-noise and https://github.com/litebird/litebirdXS4/pull/11

**Comment by carronj** [comment]
Hi, the entire repo I find slightly messy. The chwide noise maps only requires numpy, I could put this file elsewhere more easily accessible. The CMB maps construction now uses the instrument model which LiteBird keeps private as far as I know, but if OK I can just hardcode the numbers in another standalone file. Do you want me to put two standalone  files somewhere else in this repo ? where?

**Comment by zonca** [comment]
> Hi, the entire repo I find slightly messy. 

Please open a separate issue with more details and we can improve that.

> The chwide noise maps only requires numpy, I could put this file elsewhere more easily accessible. The CMB maps construction now uses the instrument model which LiteBird keeps private as far as I know, 

No, the instrument model at https://github.com/litebird/litebirdXS4-private is supposed to be accessible to all `CMB-S4xLitebird` members, @1cosmologist please ask @giuspugl for access.

> but if OK I can just hardcode the numbers in another standalone file. Do you want me to put two standalone files somewhere else in this repo ? where?

Please no, let's not duplicate numbers

**Comment by zonca** [comment]
@1cosmologist https://github.com/litebird/litebirdXS4/blob/master/20240124_chwide-noise/chwide_maps.py only requires `numpy` so it is fine.
All other questions in this issue have been answered, so I a closing this.
@1cosmologist if there is any other problem, please open another issue and be more specific in exactly what the problems are.
