### ISSUE TITLE
Rotate the LiteBIRD CMB maps in get_lb_map

### ISSUE THREAD

**Issue by 1cosmologist** [litebird/litebirdXS4#14]
The noise and foreground for CMB-S4 are in Equatorial coordinates while for LiteBIRD are in Galactic coordinates. The CMB maps fetched through `maps` package needs a relative rotation between the LiteBIRD and CMB-S4 CMB maps. This is cheaper to implement on the LiteBIRD maps as they are at a lower resolution (hence lower `lmax`). We need a `rotate_alm` stage in `get_lb_map` to convert from Equatorial to Galactic coordinates.

@antolonappan Please add any requirements that I may have missed.

**Comment by zonca** [comment]
Please add a link to the maps package, I would like to notify the mailing list about this issue and see if anyone volunteers to implement this.

**Comment by 1cosmologist** [comment]
Maps package: https://github.com/litebird/litebirdXS4/tree/9f89ccbf90053e3b87bc60480a8e5cd51aee563f/20231018_signal_cmb

**Comment by carronj** [comment]
default rotation to galactic in get_lb_map seems simple enough that I can do this tomorrow

**Comment by antolonappan** [comment]
I have a [tweak](https://github.com/antolonappan/litebirdXS4/blob/master/20231018_signal_cmb/maps.py) in my local repo, shall I do PR?

**Comment by zonca** [comment]
yes, of course
