### ISSUE TITLE
Standard Nside of maps

### ISSUE THREAD

**Issue by zonca** [litebird/litebirdXS4#2]
@giuspugl do you have a standard Nside you run your simulations at? either same or different for each channel.
For comparison, S4 does 512 for SAT 4096 for LAT, SO varies by channel: https://github.com/simonsobs/map_based_simulations/blob/master/mbs-s0012-20230321/simonsobs_instrument_parameters_2023.03/so_default_resolution.csv

**Comment by giuspugl** [comment]
@zonca  we have recently realized that we need to run at nside 512 most of the low freq. channels, but for channels at >200 GHz we need to go with 1024, as pixelization effects rises with lower reso.
